### ISSUE TITLE
Collapsable text / code folding

### ISSUE THREAD

**Issue by toddmedema** [Fabricate-IO/expedition-quest-creator#113]
Now that we have creators writing long, extensive quests, it'd be a real benefit to them to be able to collapse sections. I'm picturing that collapse arrows would be visible on the left hand gutter at the start of each card, and clicking would hide the whole card (and all sub cards). For example, clicking at the top of a roleplaying card would hide the roleplay text, all choices, and all cards nested inside of the choices (but would still show the first line of the collapsed card)

Come to think of it, it'd also end up being a handy tool for debugging branching issues...

**Comment by danielwiktorczyk** [comment]
It would also be useful to have something that would group together primary cards that hold the sub branches, as a sort of Chapter organizer. Something like

```
# Chapter 1: The Chase

_Card1_

  and all Card1's sub branches

_Card2_ 

  and all Card2's sub branches

# Chapter 2: The Confrontation

_Card3_

  and all Card3's sub branches

  **end**
```

Note: in this case, I only used # for the notation because it already seems to be condensable in the quest writer as the # quest title, so notation could be anything.

**Comment by toddmedema** [comment]
Did some research on it this morning - looks like Ace has built-in support for code folding: https://cloud9-sdk.readme.io/docs/code-folding (though we'll still have to figure out the regexs to calculate the start and end of the fold)
